### ISSUE TITLE
Possible improvement for MIDI breakout board

### ISSUE THREAD

**Issue by Kirtai** [tebl/BulkyMIDI-32#1]
Regarding the MIDI breakout board, there's a design here:

https://diyelectromusic.wordpress.com/2021/05/06/universal-microcontroller-midi-module/

that supports both 3.3v and 5v. Might be useful. :)

(It also contains a low pass filter for some reason)

BTW, I'm very impressed with what you've done so far :)

**Comment by tebl** [comment]
Thanks I'll keep it mind. So far I've only tested the waters beyond 5v
systems, but there's more and more interesting things happening beyond it
so before long I think I will need to revisit the idea 😀

tir. 9. aug. 2022, 00:58 skrev Kirtai ***@***.***>:
