### ISSUE TITLE
MIDI32 Play - Play all from folder

### ISSUE THREAD

**Issue by Magnetrix** [tebl/BulkyMIDI-32#6]
Hi there,

I'm delighted with your products. I have a Bulky Midi32 and a Bulky MIDI32 Play...

So, are you considering to add sub-folders support to add midi collections?

And how to play all files from root / sub-folders ???

Regards

**Comment by tebl** [comment]
I started on it at some point, but I started running out of memory on the
Arduino - path strings quickly add up.

Maybe if I change it to run on an ESP32, if the libraries support it. That
though, is probably a long way off.

Anyway, the code is there if you want to make an attempt at modifying it 😀

fre. 15. nov. 2024, 11:23 skrev Magnetrix ***@***.***>:
